</arm/mkfile

hellol: hello.$O world.$O
	$LD -o $target $prereq        

%.$O: %.s
	$AS $stem.s

TOP=../../..

TARGET=$TOP/ROOT/tests/5l

install:V:
	mkdir -p $TARGET; cp *.s mkfile $TARGET

clean:V:
	rm -f *.[$OS] [$OS].out hellol

run:V:
    echo :c | 5i hellol
