TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=mk

OFILES=\
    globals.$O\
    utils.$O\
    dumpers.$O\
	archive.$O\
	bufblock.$O\
	env.$O\
	file.$O\
	graph.$O\
	lex.$O\
	main.$O\
	match.$O\
	mk.$O\
	parse.$O\
	rc.$O\
	recipe.$O\
	rule.$O\
	run.$O\
	shprint.$O\
	symtab.$O\
	var.$O\
	varsub.$O\
	word.$O\

HFILES=fns.h mk.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

<$TOP/mkfiles/mkone
