TOP=../../

DOC=iwp9
SYNCWEB=syncweb

pdf:V: $DOC.pdf

$DOC.pdf: $DOC.tex $TOP/docs/latex/Config.tex
   pdflatex $DOC.tex
   bibtex $DOC
   pdflatex $DOC.tex
   pdflatex $DOC.tex

$DOC.tex:D: $DOC.nw
	$SYNCWEB -to_tex $DOC.nw defs_and_uses.list
