# -*- sh -*-
TOP=..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang C

VERSION=1
DOC=Profiler

# must be in the same order than the #include in $DOC.nw for syncweb to work
SRC_ORIG=Profiler.nw Profiler_extra.nw

#lib_core/libc/profile.c!! tos.h!! trace.h
SRC_VIEWS= \
  misc/time.c\
  misc/kprof.c\
  misc/prof.c\
  misc/trace.c\
  misc/tprof.c\
  misc/stats.c\
  iostats/statfs.h\
  iostats/globals.c\
  iostats/iostats.c\
  iostats/statsrv.c\

<$TOP/docs/latex/mkcommon

DEPS=arch core io   graphics ipc   debug devel 
INCLUDES=${DEPS:%=../include/%}
index:V:
	$INDEXER $INCLUDES misc iostats \
    | sed -e 's#/Users/pad/github/fork-plan9/##' \
    | sed -e 's#profilers/##' \
    | sed -e 's#include/XXX#include#' \
    | grep -v 'include/' \
    > defs_and_uses.list
