# -*- sh -*-
TOP=..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang C

VERSION=1
DOC=Profiler

# set of noweb (.nw) files
# must be in the same order of the #include for syncweb multi files support
# to work
SRC_ORIG=Profiler.nw Profiler_extra.nw

#lib_core/libc/profile.c!! tos.h!! trace.h
SRC_VIEWS= \
  misc/time.c\
  misc/kprof.c\
  misc/prof.c\
  misc/trace.c\
  misc/tprof.c\
  misc/stats.c\
  iostats/statfs.h\
  iostats/globals.c\
  iostats/iostats.c\
  iostats/statsrv.c\

<$TOP/docs/latex/mkcommon

index:V:
	/home/pad/github/syncweb/indexer/indexer ../include/nothing misc iostats | sed -e 's#/Users/pad/github/fork-plan9/##' | sed -e 's#include/XXX#include#'  > defs_and_uses.list
