TOP=../..
<$TOP/mkfiles/$objtype/mkfile

DIRS=port $CPUS

default:V:	all

all install:QV:
	for(i in port $objtype)@{
		cd $i
		sleep 1
		mk $MKFLAGS $target
	}

uninstall:V:
	rm -f $ROOT/$objtype/lib/libmp.a

clean:QV:
	for(i in $DIRS)@{
		cd $i
		mk $MKFLAGS $target
	}

nuke:V: clean
	rm -f $ROOT/$objtype/lib/libmp.a


installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install

everything:V:
	rm -f */*.[012456789kvx]
	for(objtype in 386)@{
		echo $objtype
		mk $MKFLAGS install
	}
	rm -f */*.[012456789kvx]

test.$O: test.c /$objtype/include/u.h /sys/include/mp.h port/dat.h
	$CC -Iport test.c

$O.test: test.$O /$objtype/lib/libmp.a
	$LD -o $O.test test.$O

bigtest.$O: bigtest.c /$objtype/include/u.h /sys/include/mp.h port/dat.h
	$CC -Iport bigtest.c

$O.bigtest: bigtest.$O /$objtype/lib/libmp.a
	$LD -o $O.bigtest bigtest.$O

allout:
	objtype=386; mk; mk 8.test 8.bigtest
	objtype=power; mk; mk q.test q.bigtest
	objtype=mips; mk; mk v.test v.bigtest

cleanout:
	rm -f [qv8].* *.[qv8]
