TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=getflags usage

<$TOP/mkfiles/mkmany

#ugly: can't be 'aux' because 'aux' is interpreted in a special way
# in VFAT filesystems
BIN=$ROOT/arch/$objtype/bin/auxrc

install:V:
	mkdir -p $BIN
	for (i in $TARG)
		mk $MKFLAGS $i.install
