TOP=../..
<$TOP/mkfiles/$objtype/mkfile

## it seems like a bad idea to include '.'
## in the path with executables like 'rm'
## in this directory.
#path=/bin

TARG=\
	conf\
	get\
	fs\
	log\
	query\
	repack\
	save\
	send\
	serve\
	walk

RC=\
	add\
	branch\
	clone\
	commit\
	compat\
	diff\
	export\
	hist\
	import\
	init\
	merge\
	pull\
	push\
	rebase\
	revert\
	rm

OFILES=\
	delta.$O\
	objset.$O\
	ols.$O\
	pack.$O\
	proto.$O\
	util.$O\
	ref.$O

HFILES=git.h

<$TOP/mkfiles/mkmany

BIN=$ROOT/arch/$objtype/bin/git

# Override install target to install rc.
install:V:
	mkdir -p $BIN
	for (i in $TARG)
		mk $MKFLAGS $i.install
	for (i in $RC)
		mk $MKFLAGS $i.rcinstall

%.rcinstall:V:
	cp $stem $BIN/$stem
	chmod +x $BIN/$stem

xxx:V:
     for (i in $RC)
          mv $i $i.rc
