TOP=../../../..
APE=$TOP/APE
<$APE/config

LIBNAME=ape/libap.a
OFILES=\
	getgrent.$O\
	getpwent.$O\
	locale.$O\
	mkfifo.$O\
	pathconf.$O\
	sigset.$O\
	sysconf.$O\
	tzset.$O\

<$TOP/mkfiles/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE -I$APE/include -I$APE/include/$objtype
