TOP=..

DIRS=libframe libplumb libcomplete  rio plumb 
# misc contains only rc scripts

<$TOP/mkfiles/mkdirs

#-----------------------------------------------------------------------------

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang C

VERSION=6
DOC=Windows

SRC_ORIG=Windows.nw Windows_extra.nw

# I use indented entries below for files that I created and I tried to put
#  them under the file they originally came from
SRC_VIEWS= \
   ../ROOT/tests/rio/hellorio.c \
   rio/dat.h\
    rio/globals.c\
   rio/fns.h\
   rio/rio.c\
    rio/thread_keyboard.c \
    rio/thread_mouse.c \
    rio/threads_misc.c \
    rio/wm.c \
    rio/error.c \
   rio/data.c\
   rio/wind.c\
    rio/threads_window.c \
    rio/terminal.c \
    rio/snarf.c \
    rio/cursor.c \
    rio/processes_winshell.c \
    rio/graphical_window.c \
   rio/fsys.c\
    rio/9p.c \
    rio/proc_fileserver.c \
   rio/scrl.c\
   \
   rio/threads_worker.c \
   \
   rio/time.c\
   rio/util.c\
   rio/wctl.c\
   rio/xfid.c\
   \
   ../applications/misc/lens.c\
   ../applications/misc/statusbar.c\
   ../applications/misc/winwatch.c\
   \
   ../include/strings/complete.h\
   ../include/gui/frame.h\
   ../include/ipc/plumb.h\
   \
   libcomplete/complete.c\
   \
   libframe/frbox.c\
   libframe/frdelete.c\
   libframe/frdraw.c\
   libframe/frinit.c\
   libframe/frinsert.c\
   libframe/frptofchar.c\
   libframe/frselect.c\
   libframe/frstr.c\
   libframe/frutil.c\
   \
   libplumb/event.c\
   libplumb/mesg.c\
   libplumb/plumbsendtext.c\

#   ../lib_graphics/libmemdraw/hwdraw.c\
#   ../kernel/devices/screen/386/cga.c\
#   codegraph.h

<$TOP/docs/latex/mkcommon

DEPS=arch core   graphics ipc gui strings
INCLUDES=${DEPS:%=../include/%}
index:V:
	$INDEXER $INCLUDES  rio libframe libplumb libcomplete \
    | sed -e 's#/Users/pad/github/fork-plan9/##' \
    | sed -e 's#include/XXX#include#' \
    | grep -v 'include/' \
    > defs_and_uses.list
