TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=acid

UOFILES=	main.$O\
        globals.$O\
	lex.$O\
	util.$O\
	exec.$O\
	expr.$O\
	list.$O\
	builtin.$O\
	proc.$O\
	dot.$O\
	print.$O\

OFILES=$UOFILES y.tab.$O

YFILES=dbg.y

HFILES=acid.h

<$TOP/mkfiles/mkone

lex.$O:		y.tab.h
util.$O:	y.tab.h
builtin.$O:	y.tab.h
main.$O:	y.tab.h
