TOP=../..
<$TOP/mkfiles/$objtype/mkfile

<$TOP/mkfiles/mkmanyauto

# the clean regexp in mkmany is [$OS].??* so it assumes the program has
# more than 2 characters, but here we have a program called p.c
CLEANFILES=5.p 8.p
