TOP=../../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=ether

OFILES=\
	main.$O\

LIBDOFILES=\
	ether.$O\
	asix.$O\
	smsc.$O\
	cdc.$O\

HFILES=\
	ether.h\
	../lib/usb.h\
	../lib/usbfs.h\

LIBD=../lib/usbdev.a$O
LIBU=../lib/usb.a$O
LIB=\
	$LIBD\
	$LIBU\


<$TOP/mkfiles/mkone

BIN=/$objtype/bin/usb
CFLAGS=-I../lib $CFLAGS

$LIBU:
	cd ../lib
	mk install
	mk clean

$LIBD:V: $LIBDOFILES
	iar vu $LIBD $LIBDOFILES
