TOP=../../..
objtype=386
<$TOP/mkfiles/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libsec.a

FILES=\
	md5block\
	sha1block\

HFILES=$TOP/include/ALL/libsec.h

OFILES=${FILES:%=%.$O}

<$TOP/mkfiles/mksyslib
