# -*- sh -*-
TOP=..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang C

VERSION=2
DOC=Debugger

# must be in the same order than the #include in $DOC.nw for syncweb to work
SRC_ORIG=Debugger.nw Debugger_extra.nw Debugger_x86.nw

#TODO: acid/dbg.y cc/acid.c?
# TODO misc/leak misc/kmem? misc/umem? snap?
SRC_VIEWS= \
   tracers/ktrace.c\
   tracers/strace.c\
   \
   db/defs.h\
   db/fns.h\
   db/utils.c\
   db/globals.c\
   db/output.c\
   db/input.c\
   db/setup.c\
   db/format.c\
   db/regs.c\
   db/expr.c\
   db/trcrun.c\
   db/print.c\
   db/command.c\
   db/runpcs.c\
   db/pcs.c\
   db/main.c\
   \
   acid/acid.h\
   acid/globals.c\
   acid/lex.c\
   acid/main.c\
   acid/util.c\
   acid/exec.c\
   acid/proc.c\
   acid/list.c\
   acid/dot.c\
   acid/print.c\
   acid/expr.c\
   acid/builtin.c\
  \
  ../include/debug/mach.h\
  ../include/exec/bootexec.h\
  \
  libmach/5.c\
  libmach/5db.c\
  libmach/5obj.c\
  libmach/elf.h\
  libmach/obj.h\
  libmach/swap.c\
  libmach/executable.c\
  libmach/map.c\
  libmach/sym.c\
  libmach/access.c\
  libmach/machdata.c\
  libmach/obj.c\
  libmach/setmach.c\

XX=\
  libmach/8.c\
  libmach/8db.c\
  libmach/8obj.c\

# not acid/y.tab.[ch]

<$TOP/docs/latex/mkcommon

DEPS=core arch/arm io    ipc   debug
INCLUDES=${DEPS:%=../include/%}
index:V:
	$INDEXER $INCLUDES db acid tracers libmach \
    | sed -e 's#/Users/pad/github/fork-plan9/debuggers/##' \
    | sed -e 's#include/XXX#include#' \
    > defs_and_uses.list
