TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=mothra

CFILES= \
	snoop.c \
	forms.c \
	getpix.c \
	html.syntax.c \
	mothra.c \
	rdhtml.c \
	url.c \

OFILES=${CFILES:%.c=%.$O} version.$O
HFILES=mothra.h html.h $TOP/include/ALL/panel.h $TOP/include/ALL/rtext.h

<$TOP/mkfiles/mkone

CFLAGS=-Dplan9 $CFLAGS

version.c:	$CFILES
	date|sed 's/^... //;s/ +/-/g;s/.*/char version[]="&";/' >version.c
