TOP=../..

VERSION=9
DOC=Principia

SRC_ORIG=Principia.nw ed.nw oed.nw
SRC_VIEWS=$TOP/editors/ed/ed.c
SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang C

<$TOP/docs/latex/mkcommon

#TODO:
index:V:
	touch defs_and_uses.list
