TOP=../..

VERSION=1.0
DOC=Principia

SRC_ORIG=Principia.nw ../../editors/ed.nw
# oed.nw
SRC_VIEWS=$TOP/editors/ed/ed.c
SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang C

<$TOP/docs/latex/mkcommon

#TODO:
index2:V:
	cd ../../editors; syncweb_indexer -lang c ed/ > ../docs/principia/defs_and_uses.list
