TOP=../..

DOC=Principia
VERSION=1.2
SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang C

SRC_ORIG=Principia.nw ../../editors/ed.nw # oed.nw
SRC_VIEWS=$TOP/editors/ed/ed.c

<$TOP/docs/latex/mkcommon

index:V:
	cd ../../editors; syncweb_indexer -lang c ed/ > ../docs/principia/defs_and_uses.list
