</$objtype/mkfile

# I moved many stuff in ../<protocol>/
TARG=6in4\
	gping\
	hogports\
	linklocal\
	ping\
	rexexec\
	rip\
	rlogind\
	traceroute\
	udpecho\
	wol\

DIRS=ipconfig

BIN=/$objtype/bin/ip
HFILES=icmp.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=%.c}\

</sys/src/cmd/mkmany

all:V:	$DIRS

$DIRS:V:
	for (i in $DIRS) @{
		echo DIR: `{pwd}^/$i
		cd $i
		mk all
	}
        echo DIR: `{pwd}

install:V:	installdirs

installdirs:V:
	for (i in $DIRS) @{
		echo mk $i
		cd $i
		mk install
	}

update:V:
	update $UPDATEFLAGS $UPDATE
	for (i in $DIRS) @{
		echo update $i
		cd $i
		mk 'UPDATEFLAGS='$"UPDATEFLAGS update
	}

clean:V:
	for (i in $DIRS) @{
		echo clean $i
		cd $i
		mk clean
	}
	rm -f [$OS].* *.[$OS]

nuke:V:
	for (i in $DIRS) @{
		echo nuke $i
		cd $i
		mk nuke
	}
	rm -f *.[$OS] y.tab.? y.debug y.output [$OS].$TARG $TARG

$O.fakearp:	fakearp.$O getether.$O
	$LD -o $target $prereq


$BIN/snoopy:V:	$O.snoopy
	cp $prereq /$objtype/bin/snoopy

$BIN/sniffer:V:	$O.sniffer
	cp $prereq /$objtype/bin/sniffer
