TOP=../..
<$TOP/mkfiles/$objtype/mkfile

# I moved many stuff in ../<protocol>/
TARG=6in4\
	gping\
	hogports\
	linklocal\
	ping\
	rexexec\
	rip\
	rlogind\
	traceroute\
	udpecho\
	wol\

DIRS=ipconfig

HFILES=icmp.h

<$TOP/mkfiles/mkdirsmany

$O.fakearp:	fakearp.$O getether.$O
	$LD $LDFLAGS -o $target $prereq

$BIN/snoopy:V:	$O.snoopy
	cp $prereq $ROOT/$objtype/bin/snoopy

$BIN/sniffer:V:	$O.sniffer
	cp $prereq $ROOT/$objtype/bin/sniffer
