TOP=../../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=kb

OFILES=main.$O

LIBDOFILES=kb.$O\
	hid.$O

HFILES=\
	../lib/usb.h\
	hid.h\

LIBD=../lib/usbdev.a$O
LIBU=../lib/usb.a$O
LIB=\
	$LIBD\
	$LIBU\


<$TOP/mkfiles/mkone

BIN=/$objtype/bin/usb
CFLAGS=-I../lib $CFLAGS

$LIBU:
	cd ../lib
	mk install
	mk clean

$LIBD:V: $LIBDOFILES
	iar vu $LIBD $LIBDOFILES

