</arm/mkfile

all:V: float1 float2

float1: float.$O
	$LD -o $target $prereq        

float2: float.$O
	$LD -f -o $target $prereq        

%.$O: %.c
	$CC $CFLAGS $stem.c


clean:V:
	rm -f *.[$OS] [$OS].out float1 float2
