</$objtype/mkfile

#old: DIRS=`{ls -l | sed '/^d/!d; s/.* //; /\./d'}
#TODO: draw fmt l mp net regexp sec utf v
DIRS=ap bsd 9

none:V:
	echo mk all, install, installall, clean, or nuke

all clean nuke install installall:V:
	for (i in $DIRS) @{
		cd $i
		mk $target
	}
