TOP=../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=dhcpd\
	dhcpleases\

DOFILES=\
	dhcpd.$O\
	db.$O\
	ndb.$O\
	ping.$O\

IOFILES=\
	dhcpleases.$O\
	db.$O\
	ping.$O\

HFILES=dat.h ../dhcp.h ../../ip/icmp.h

<$TOP/mkfiles/mkmany

$O.dhcpd: $DOFILES
	$LD $LDFLAGS -o $target $DOFILES

$O.dhcpleases: $IOFILES
	$LD $LDFLAGS -o $target $IOFILES

$O.testping: testping.$O ping.$O
	$LD $LDFLAGS -o $target $prereq
