</$objtype/mkfile

TARG=5l
OFILES=globals.$O\
	asm.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	compat.$O\
	elf.$O\

#PAD	../5c/5.out.h\

HFILES=\
	l.h\
	../8l/elf.h\

BIN=/$objtype/bin
CFLAGS=$CFLAGS -. -I.
</sys/src/cmd/mkone

#PAD:../5c/5.out.h
#../5c/enam.c: 
#	@ { cd ../5c; mk enam.c }

#enam.$O:	../5c/enam.c
#	$CC $CFLAGS ../5c/enam.c

elf.$O:	../8l/elf.c
	$CC $CFLAGS ../8l/elf.c

x:V:	$O.out
	$O.out -la -o/dev/null x.5
