TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIBNAME=libip.a

OFILES=\
	eipfmt.$O\
	equivip.$O\
	parseip.$O\
	parseether.$O\
	myetheraddr.$O\
	myipaddr.$O\
	classmask.$O\
	bo.$O\
	readipifc.$O\
	ipaux.$O\
	ptclbsum.$O\

HFILES=$TOP/include/ALL/ip.h

<$TOP/mkfiles/mksyslib
