TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libip.a

OFILES=\
	eipfmt.$O\
	equivip.$O\
	parseip.$O\
	parseether.$O\
	myetheraddr.$O\
	myipaddr.$O\
	classmask.$O\
	bo.$O\
	readipifc.$O\
	ipaux.$O\
	ptclbsum.$O\

HFILES=\
	/sys/include/ip.h

<$TOP/mkfiles/mksyslib
