TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIBNAME=libflate.a

OFILES=\
	deflate.$O\
	deflatezlib.$O\
	deflateblock.$O\
	deflatezlibblock.$O\
	inflate.$O\
	inflatezlib.$O\
	inflateblock.$O\
	inflatezlibblock.$O\
	flateerr.$O\
	crc.$O\
	adler.$O\

HFILES=	$TOP/include/ALL/flate.h zlib.h

<$TOP/mkfiles/mksyslib
