< /$objtype/mkfile
BIN=/$objtype/bin/aux

TARG=vga
OFILES=\
	clgd542x.$O\
	data.$O\
	db.$O\
	error.$O\
	io.$O\
	main.$O\
	palette.$O\
	pci.$O\
	vesa.$O\
	vesadb.$O\
	vga.$O\

HFILES=\
	pci.h\
	vga.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	/lib/vgadb\
	riva_tbl.h\


</sys/src/cmd/mkone

