TOP=../../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=vga

OFILES=\
	clgd542x.$O\
	data.$O\
	db.$O\
	error.$O\
	io.$O\
	main.$O\
	palette.$O\
	pci.$O\
	vesa.$O\
	vesadb.$O\
	vga.$O\

HFILES= pci.h vga.h

<$TOP/mkfiles/mkone
