TOP=../../..
objtype=386
<$TOP/mkfiles/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libmp.a

SFILES=\
	mpvecadd.s\
	mpvecdigmuladd.s\
	mpvecdigmulsub.s\
	mpvecsub.s\
	mpdigdiv.s\

HFILES=$TOP/include/arch/$objtype/u.h $TOP/include/ALL/mp.h ../port/dat.h

OFILES=${SFILES:%.s=%.$O}

<$TOP/mkfiles/mksyslib
