TOP=../..
<$TOP/mkfiles/$objtype/mkfile

PORTDIRS=9sys 9syscall fmt port
DIRS=$PORTDIRS $CPUS

all install:QV:
	for(i in $PORTDIRS $objtype)@{
		cd $i
		mk $MKFLAGS install
	}

clean:QV:
	for(i in $DIRS)@{
		cd $i
		mk $MKFLAGS $target
	}

nuke:QV:
	for(i in $PORTDIRS $objtype)@{
		cd $i
		mk $MKFLAGS nuke
	}
	# do not nuke other objtypes
	for(i in $CPUS)@{
		cd $i
		mk $MKFLAGS clean
	}

uninstall:V:
	rm -f $ROOT/$objtype/lib/libc.a


installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install

everything:V:
	rm -f */*.[0245689kqv]
	for(objtype in $CPUS)@{
		echo $objtype
		mk $MKFLAGS install
	}
	rm -f */*.[0245689kqv]
