# -*- sh -*-
TOP=..

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml

VERSION=1
DOC=Efuns

SRC_ORIG=Efuns.nw Efuns_extra.nw

EFUNS=/home/pad/github/fork-efuns

SRC_VIEWS= XXX

<$TOP/docs/latex/mkcommon

index:V:
	$INDEXER -lang cmt $EFUNS \
    | sed -e 's#main.cmt#Main#' \
    | grep -v 'Common.=~' \
    > defs_and_uses.list
