TOP=..

DIRS=misc samterm sam acme

<$TOP/mkfiles/mkdirs

#-----------------------------------------------------------------------------

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml

VERSION=3
DOC=Editor

SRC_ORIG=Editor.nw Editor_extra.nw

EFUNS=/home/pad/github/fork-efuns

#to lpize at some point:
# dircolors.ml, shell.ml, outline_mode.ml, prog_modes/*, etc

SRC= \
  commons/store.ml\
  commons/store.mli\
  \
  core/efuns.ml\
   core/var.ml\
   core/attr.ml\
   core/hook.ml\
   core/action.ml\
   core/globals.ml\
  core/text.ml\
  core/ebuffer.ml\
  core/keymap.ml\
  core/window.ml\
  core/frame.ml\
  core/top_window.ml\
  \
  features/simple.ml\
   features/mouse.ml\
   features/highlight.ml\
   features/parameter.ml\
   features/indent.ml\
   features/structure.ml\
  features/minibuffer.ml\
  features/complexe.ml\
  features/system.ml\
  features/select.ml\
  features/search.ml\
  features/interactive.ml\
  features/multi_buffers.ml\
  features/multi_frames.ml\
  features/abbrevs.ml\
  features/compil.ml\
  \
  std_efunsrc.ml\
  main.ml\
  \
  major_modes/dired.ml\
  \
  minor_modes/minor_mode_sample.ml\
  minor_modes/abbrevs_mode.ml\
  minor_modes/accents_mode.ml\
  minor_modes/fill_mode.ml\
  minor_modes/paren_mode.ml\
  minor_modes/tab_mode.ml\
  \
  prog_modes/makefile_mode.ml\
  prog_modes/ocaml_toplevel.ml\
  \
  ipc/server.ml\
  ipc/efuns_client.ml\
  \
  todo/dynamic/eval.ml\
  todo/misc/efuns_filebrowser.ml\
  todo/misc/efuns_texbrowser.ml\

SRC_VIEWS=${SRC:%=$EFUNS/%}

<$TOP/docs/latex/mkcommon

#TODO: lpize the .ml and modules mentioned below in the grep -v
index:V:
	$INDEXER -lang cmt $EFUNS \
    | sed -e 's#main.cmt#Main#' \
    | grep -v 'Common.=~' \
    | grep -v 'Options.=:=' \
    | grep -v 'Xtypes|Xdraw|Str2|xK.ml|graphics_efuns.ml' \
    | grep -v 'utils.ml|options.ml|log.ml|concur.ml' \
    | grep -v 'tex_mode.ml|org_mode.ml|html_mode.ml' \
    | grep -v 'pl_colors.ml|ocaml_mode.ml|lisp_mode.ml|c_mode.ml' \
    | grep -v 'shell.ml|outline_mode.ml|buffer_menu.ml|dircolors.ml' \
    | grep -v 'pad.ml' \
    > defs_and_uses.list
