</$objtype/mkfile

TARG=8c
OFILES=globals2.$O\
	cgen.$O\
	cgen64.$O\
	div.$O\
	enam.$O\
	list.$O\
	machcap.$O\
	mul.$O\
	peep.$O\
	pgen.$O\
	pswt.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\

#PAD:	8.out.h\

HFILES=\
	gc.h\
	../cc/cc.h\

LIB=../cc/cc.a$O

BIN=/$objtype/bin
</sys/src/cmd/mkone

$LIB:
	cd ../cc
	mk install
	mk clean


%.$O: ../cc2/%.c
	$CC $CFLAGS ../cc2/$stem.c
