TOP=../../..
APE=$TOP/APE
<$APE/config

LIBNAME=ape/libutf.a
OFILES=\
	rune.$O\
	runestrcat.$O\
	runestrchr.$O\
	runestrcmp.$O\
	runestrcpy.$O\
	runestrdup.$O\
	runestrecpy.$O\
	runestrlen.$O\
	runestrncat.$O\
	runestrncmp.$O\
	runestrncpy.$O\
	runestrrchr.$O\
	runestrstr.$O\
	runetype.$O\
	utfecpy.$O\
	utflen.$O\
	utfnlen.$O\
	utfrrune.$O\
	utfrune.$O\
	utfutf.$O\

<$TOP/mkfiles/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE -I$APE/include -I$APE/include/$objtype
