TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIBNAME=libbio.a

OFILES=\
	bbuffered.$O\
	bfildes.$O\
	bflush.$O\
	bgetrune.$O\
	bgetc.$O\
	bgetd.$O\
	binit.$O\
	boffset.$O\
	bprint.$O\
	bputrune.$O\
	bputc.$O\
	brdline.$O\
	brdstr.$O\
	bread.$O\
	bseek.$O\
	bwrite.$O\
	bvprint.$O\

HFILES=$TOP/include/ALL/bio.h

<$TOP/mkfiles/mksyslib
