TOP=../..
<$TOP/mkfiles/$objtype/mkfile

# default domain for faces, overridden by $facedom
DEFAULT="pad"

TARG=faces

OFILES=main.$O\
	facedb.$O\
	plumb.$O\
	util.$O\

HFILES=faces.h\

<$TOP/mkfiles/mkone
CFLAGS=$CFLAGS '-DDEFAULT='$DEFAULT

$O.dblook: dblook.$O facedb.$O util.$O
	$LD $LDFLAGS -o $target $prereq
