TOP=../../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=usbd

OFILES=\
	usbd.$O\
	dev.$O\
	devtab.$O\

HFILES=\
	usbd.h\
	../lib/usb.h\
	../lib/usbfs.h\

LIBD=../lib/usbdev.a$O
LIBU=../lib/usb.a$O
LIB=\
	$LIBD\
	$LIBU\

<$TOP/mkfiles/mkone

BIN=/$objtype/bin/usb
CFLAGS=-I../lib $CFLAGS

$LIBU:
	cd ../lib
	mk install
	mk clean

devtab.c: usbdb ../lib/usb.h mkdev
	rc ./mkdev >$target

#alt: do not add devtab.c in repo and clean it automatically
# but simpler for now to commit it because I have problems to
# run mkdev with goken's rc and goken's utilities so KISS
# and add it to the repo
#CLEANFILES=devtab.c
