TOP=../../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=usbd

OFILES=\
	usbd.$O\
	dev.$O\
	devtab.$O\

HFILES=\
	usbd.h\
	../lib/usb.h\
	../lib/usbfs.h\

LIBD=../lib/usbdev.a$O
LIBU=../lib/usb.a$O
LIB=\
	$LIBD\
	$LIBU\

<$TOP/mkfiles/mkone

BIN=/$objtype/bin/usb
CFLAGS=-I../lib $CFLAGS

$LIBU:
	cd ../lib
	mk install
	mk clean

devtab.c: usbdb ../lib/usb.h mkdev
	./mkdev >$target

CLEANFILES=devtab.c
