TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=grap

OFILES=\
	grap.$O\
	grapl.$O\
	main.$O\
	input.$O\
	print.$O\
	frame.$O\
	for.$O\
	coord.$O\
	ticks.$O\
	plot.$O\
	label.$O\
	misc.$O\

HFILES=grap.h y.tab.h

YFILES=grap.y

LFILES=grapl.lx

<$TOP/mkfiles/mkone

CC=pcc
LD=pcc
YFLAGS= -d -S
CFLAGS=-FTV -c -I$TOP/APE/include -I$TOP/APE/include/$objtype
# claude: the .../lib (not .../lib/ape) entry is for libl.a, pulled in
# by lex's own generated ncform driver via #pragma lib "libl.a"
LDFLAGS=-L$TOP/ROOT/arch/$objtype/lib/ape -L$TOP/ROOT/arch/$objtype/lib

grap.c:	y.tab.c
	mv $prereq $target

grapl.c:	$LFILES
	$LEX -t $prereq > $target

CLEANFILES=grapl.c grap.c

