MKSHELL=$PLAN9/bin/rc

ARCH=\
	pc\
	bcm\

all:V:
	for(i in $ARCH)@{
		cd $i
		mk
	}

installall install:V:
	for(i in $ARCH) @{
		cd $i
		mk $target
	}

clean:V:
	for(i in $ARCH) @{
		cd $i
		mk clean
	}
