
#alt: TOP=../../..
#<$TOP/mkfiles/arm/mkfile
LD=5l
AS=5a
O=5
OS=5

all:V: hellol1
#hellol3 hellol2 hellol1

hellol3: hello3.$O world3.$O
	$LD -o $target $prereq        

hellol2: hello2.$O world.$O
	$LD -o $target $prereq /arm/lib/libc.a

hellol1: hello.$O world.$O
	$LD -o $target $prereq        

%.$O: %.s
	$AS $stem.s

%.$O: %.c
	$CC -I/arm/include -I/sys/include $stem.c

clean:V:
	rm -f *.[$OS] [$OS].out hellol1 hellol2

run:V:
    echo :c | 5i hellol1
