</$objtype/mkfile

TARG=`{ls *.c | sed 's/..$//'}
DIRS=faces

</sys/src/cmd/mkmany

all:V: $DIRS

$DIRS:V:
	for(i in $DIRS) @{cd $i; echo DIR: `{pwd}; mk all }
clean:V:
	for(i in $DIRS) @{cd $i; mk clean }
	rm -f [$OS].* *.[$OS]
