TOP=../..
<$TOP/mkfiles//$objtype/mkfile

LIBNAME=libmach.a

FILES=\
	executable\
	map\
	obj\
	swap\
	sym\
	access\
	machdata\
	setmach\
        5\
	8\
        v\
        5db\
	8db\
        vdb\
        5obj\
	8obj\
        vobj\
        vcodas\

HFILES=$TOP/include/ALL/mach.h elf.h obj.h

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

<$TOP/mkfiles/mksyslib

#CFLAGS=$CFLAGS -I/sys/src/cmd

8obj.$O: $TOP/include/ALL/8.out.h
5obj.$O: $TOP/include/ALL/5.out.h
vobj.$O: $TOP/include/ALL/v.out.h
