</$objtype/mkfile

LIB=/$objtype/lib/libmach.a
FILES=\
	executable\
	map\
	obj\
	swap\
	sym\
	access\
	machdata\
	setmach\
        5\
	8\
        5db\
	8db\
        5obj\
	8obj\

HFILES=/sys/include/mach.h elf.h obj.h

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	/386/lib/libmach.a\
	$HFILES\
	$CFILES\

</sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -I/sys/src/cmd

#PAD: todo
#8obj.$O: /sys/src/cmd/8c/8.out.h
#5obj.$O: /sys/src/cmd/5c/5.out.h

