# -*- sh -*-
TOP=..

DOC=Kernel

# must be in the same order than the #includes in the main .nw file 
# (so the syncweb multi-files support can work)
SRC_ORIG=Kernel.nw Kernel_extra.nw Kernel_arm.nw Kernel_x86.nw

SRC_VIEWS= \
  ../lib_core/libc/9syscall/sys.h\
  ../include/devel/internals/trace.h\
  ../include/devel/internals/tos.h\
  ../include/arch/arm/ureg.h\
  ../include/arch/386/ureg.h\
  \
  arch/arm/dat_arch.h\
  arch/arm/io.h\
  arch/arm/coproc.c\
  arch/arm/vcore.c\
  arch/arm/arm.h\
  arch/arm/arminstr.ha\
  arch/386/dat_arch.h\
  arch/386/io.h\
  arch/386/arch.c\
  arch/386/bios32.c \
  arch/386/iomap.c \
  arch/386/l_io.s \
  arch/386/l_realmode.s \
  arch/386/mp.h \
  arch/386/mpacpi.h \
  arch/386/nvram.c \
  arch/386/realmode.c \
  arch/386/x16.ha \
  arch/386/x86.c \
  \
  buses/arm/dma.c\
  buses/arm/devusb.c\
  buses/arm/dwcotg.h\
  buses/arm/uartmini.c\
  buses/arm/usbdwc.c\
  buses/386/dma.c \
  buses/386/pci.c \
  buses/386/uarti8250.c \
  buses/386/uartisa.c \
  buses/devuart.c \
  buses/portdat_buses.h \
  buses/portfns_buses.h \
  \
  concurrency/arm/spl.s\
  concurrency/arm/concurrency_raspi1.c\
  concurrency/arm/tas_raspi1.s\
  concurrency/386/l_concurrency.s \
  concurrency/386/concurrency.c \
  concurrency/portdat_concurrency.h \
  concurrency/portfns_concurrency.h \
  concurrency/qlock.c \
  concurrency/ref.c \
  concurrency/taslock.c \
  \
  console/devcons.c \
  console/portdat_console.h \
  console/portfns_console.h \
  console/print.c \
  console/rdb.c \
  \
  core/arm/dat.h\
  core/arm/dat_core.h\
  core/arm/dat_forward.h\
  core/arm/fns.h\
  core/386/dat.h \
  core/386/dat.c \
  core/386/dat_core.h \
  core/386/dat_forward.h \
  core/386/fns.c \
  core/386/fns.h \
  core/error.h \
  core/error.c \
  core/portdat.c \
  core/portdat_core.h \
  core/portdat_forward.h \
  core/portfns.c \
  core/portfns_core.h \
  \
  devices/portdat_devices.h \
  devices/portfns_devices.h \
  devices/keyboard/portkbd.c \
  devices/keyboard/arm/kbd.c\
  devices/keyboard/386/kbd.c \
  devices/keyboard/latin1.c \
  devices/keyboard/latin1.h \
  devices/keyboard/devkbin.c \
  devices/keyboard/devkbmap.c \
  devices/mouse/devmouse.c \
  devices/mouse/portmouse.c \
  devices/mouse/386/mouse.c \
  devices/mouse/arm/mouse.c \
  devices/screen/386/cga.c \
  devices/storage/386/devfloppy.c \
  devices/storage/386/floppy.h \
  devices/storage/386/sdata.c \
  devices/storage/devsd.c \
  devices/storage/sd.h \
  devices/storage/sdscsi.c \
  devices/storage/arm/emmc.c\
  devices/sys/arm/devarch.c\
  devices/sys/386/devarch.c \
  devices/sys/386/devrtc.c \
  devices/sys/devdup.c \
  devices/sys/devenv.c \
  devices/sys/devmnt.c \
  devices/sys/devpipe.c \
  devices/sys/devproc.c \
  devices/sys/devroot.c \
  devices/sys/devsrv.c \
  devices/sys/devsys.c \
  \
  files/allocb.c \
  files/cache.c \
  files/chan.c \
  files/dev.c \
  files/env.c \
  files/file.c \
  files/mnt.c \
  files/portdat_files.h \
  files/portfns_files.h \
  files/qio.c \
  files/sysfile.c \
  \
  filesystems/devfs.c \
  \
  init/arm/bootconf.c\
  init/arm/main.c\
  init/arm/raspi1.c\
  init/arm/watchdog.c\
  init/arm/start.s\
  init/arm/startv6.s\
  init/arm/rebootcode.s\
  init/386/l.s \
  init/386/l_fp.s \
  init/386/l_misc.s \
  init/386/l_multiboot.s \
  init/386/apbootstrap.s \
  init/386/main.c \
  init/386/rebootcode.s \
  init/user/preboot/initcode.c \
  init/user/preboot/386/init9.c \
  init/user/preboot/arm/init9.s\
  init/user/boot/aux.c \
  init/user/boot/boot.c \
  init/user/boot/boot.h \
  init/user/boot/local.c \
  init/portfns_init.h \
  init/rebootcmd.c \
  \
  lib/lib.h \
  \
  memory/arm/dat_memory.h\
  memory/arm/mem.h\
  memory/arm/mmu.c\
  memory/arm/mmuinvalidate.s\
  memory/arm/cache_raspi1.s\
  memory/386/dat_memory.h \
  memory/386/mem.h \
  memory/386/memory.c \
  memory/386/mmu.c \
  memory/alloc.c \
  memory/fault.c \
  memory/page.c \
  memory/pool.c \
  memory/portdat_memory.c \
  memory/portdat_memory.h \
  memory/portfns_memory.h \
  memory/segment.c \
  memory/swap.c \
  memory/sysmemory.c \
  memory/xalloc.c \
  \
  misc/parse.c \
  misc/portdat_misc.h \
  misc/portfns_misc.h \
  misc/random.c \
  \
  processes/arm/dat_processes.h\
  processes/arm/arch.c\
  processes/arm/vfp3.c\
  processes/arm/lproc.s\
  processes/arm/switch.s\
  processes/386/dat_processes.h \
  processes/386/apic.c \
  processes/386/archgeneric.c \
  processes/386/archmp.c \
  processes/386/l_switch.s \
  processes/386/main_processes.c \
  processes/386/mp.c \
  processes/386/mpacpi.c \
  processes/edf.c \
  processes/pgrp.c \
  processes/portdat_processes.c \
  processes/portdat_processes.h \
  processes/portfns_processes.h \
  processes/proc.c \
  processes/sysproc.c \
  processes/syssema.c \
  \
  interrupts/portfns_interrupts.h \
  interrupts/arm/trap.c\
  interrupts/arm/fault_helpers.s\
  interrupts/arm/lexception.s\
  interrupts/386/trap.c \
  interrupts/386/dat_interrupts.h \
  interrupts/386/i8259.c \
  interrupts/386/l_trap.s \
  \
  time/portdat_time.h \
  time/portfns_time.h \
  time/alarm.c \
  time/portclock.c \
  time/tod.c \
  time/arm/clock.c\
  time/arm/dat_time.h\
  time/arm/time_raspi1.s\
  time/386/dat_time.h \
  time/386/i8253.c \
  time/386/time.c \
  \
  security/auth.c \
  security/portfns_security.h \
  \
  syscalls/arm/syscall.c\
  syscalls/386/plan9l.s \
  syscalls/syscallfmt.c \
  syscalls/systab.c \
  syscalls/systab.h \

# not here: 
#  - graphics files: devdraw.c, portscreen.c, swcursor.c, ...
#  - network files: ip/, netif.c, ...
#  - devices/keyboard/portkbdtab.c (latex problem if included)
#  -  non C files
#      conf/arm/mkfile
#      conf/arm/pi
#      init/user/boot/arm/boot.rc
#      docs/arm/readme.txt
#
#  - raspberry pi 2 files
#      init/arm/startv7.s
#      init/arm/raspi2.c
#      concurrency/arm/concurrency_raspi2.c
#      concurrency/arm/tas_raspi2.s
#      memory/arm/cache_raspi2.s
#      time/arm/time_raspi2.s
#      conf/arm/pi2

#visual:
#	~/pfff/codemap -ss 2 -no_legend -filter cpp .
#visual2:
#	~/pfff/codemap -ss 2 -no_legend -filter nw -ft 0.001 -nblines_file 60000 .

<$TOP/docs/latex/mkcommon
