TOP=../../../../../..
<$TOP/mkfiles/$objtype/mkfile

OFILES=\
	disk.$O\
	proto.$O\
	scsi.$O\

HFILES=$TOP/include/ALL/disk.h

LIB=$ROOT/$objtype/lib/libdisk.a

<$TOP/mkfiles/mksyslib

$O.test: test.$O $LIB
	$LD -o $target test.$O $LIB
