TOP=../../../../../..
<$TOP/mkfiles/$objtype/mkfile

LIBNAME=libdisk.a

OFILES=\
	disk.$O\
	proto.$O\
	scsi.$O\

HFILES=$TOP/include/ALL/disk.h

<$TOP/mkfiles/mksyslib

$O.test: test.$O $LIB
	$LD -o $target test.$O $LIB
