TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libframe.a

OFILES=\
	frbox.$O\
	frdraw.$O\
	frdelete.$O\
	frinit.$O\
	frinsert.$O\
	frptofchar.$O\
	frselect.$O\
	frstr.$O\
	frutil.$O\

<$TOP/mkfiles/mksyslib
