TOP=../..
<$TOP/mkfiles/$objtype/mkfile

DIRS=port $CPUS

default:V:	all

install all:QV:
	for(i in port $objtype)@{
		cd $i
		mk $MKFLAGS $target
	}

clean:QV:
	for(i in $DIRS)@{
		cd $i
		mk $MKFLAGS $target
	}

nuke:V: clean
	rm -f $ROOT/$objtype/lib/libsec.a

installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install

everything:V:
	rm -f */*.[012456789kqv]
	for(objtype in 386)@{
		echo $objtype
		mk $MKFLAGS install
	}
	rm -f */*.[012456789kqv]
