TOP=../../../..
APE=$TOP/APE
<$APE/config

LIBNAME=ape/libap.a

OFILES=\
	atom.$O\
	cycles.$O\
	div.$O\
	getfcr.$O\
	lock.$O\
	main9.$O\
	main9p.$O\
	memmove.$O\
	memset.$O\
	notetramp.$O\
	setjmp.$O\
	strchr.$O\
	strcmp.$O\
	strcpy.$O\
	tas.$O\
	vlop.$O\
	vlrt.$O\

<$TOP/mkfiles/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE -D_PLAN9_SOURCE -I$APE/include -I$APE/include/$objtype
