</arm/mkfile

helloa: helloa.$O
	$LD -o $target $prereq        

%.$O: %.s
	$AS $stem.s

TOP=../../..

TARGET=$TOP/ROOT/tests/5a

install:V:
	mkdir -p $TARGET; cp *.s mkfile $TARGET

clean:V:
	rm -f *.[$OS] [$OS].out helloa

run:V:
    echo :c | 5i helloa
