
// defined in .s
void _exits() { }
void alarm() { }
void await() { }
void bind() { }
void brk() { }
void chdir() { }
void close() { }
void create() { }
void dup() { }
void errstr() { }
void exec() { }
void fauth() { }
void fd2path() { }
void fstat() { }
void fversion() { }
void fwstat() { }
void mount() { }
void nop() { }
void noted() { }
void notify() { }
void open() { }
void pipe() { }
void pread() { }
void pwrite() { }
void remove() { }
void rendezvous() { }
void rfork() { }
void seek() { }
void segattach() { }
void segbrk() { }
void segdetach() { }
void segflush() { }
void segfree() { }
void semacquire() { }
void semrelease() { }
void sleep() { }
void stat() { }
void tsemacquire() { }
void unmount() { }
void wstat() { }
