</$objtype/mkfile

LIB=aa.a$O
OFILES=\
        globals.$O\
        utils.$O\
        error.$O\
        hist.$O\
        float.$O\
        lookup.$O\
        lexbody.$O\
        macbody.$O\

HFILES=aa.h\
	

</sys/src/cmd/mklib

install:V:	$LIB
	date

$LIB:	$LIBOBJ
	ar vu $LIB $OFILES
