</$objtype/mkfile

LIB=aa.a$O
OFILES=\
        globals.$O\
        utils.$O\
        lexbody.$O\
        compat.$O\
        macbody.$O\

HFILES=aa.h\
	

</sys/src/cmd/mklib

install:V:	$LIB
	date

$LIB:	$LIBOBJ
	ar vu $LIB $OFILES
