#alt: TOP=../../..
#<$TOP/mkfiles/386/mkfile
LD=8l
AS=8a
O=8
OS=8

all:V: hellol1

hellol1: hello.$O world.$O
	$LD -o $target $prereq

%.$O: %.s
	$AS $stem.s

clean:V:
	rm -f *.[$OS] [$OS].out hellol1

# note: unlike 5i for ARM, this repo has no x86 interpreter (see
# machine/Machine.nw: "actually there is no 8i"), so there is no
# run:V: target here -- hellol1 must be run under an actual Plan 9
# (e.g. the dosdisk.img/qemu setup).
