TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=8l

OFILES=globals.$O\
        utils.$O\
	asm.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	list.$O\
	enam.$O\
	compat.$O\
	elf.$O\

HFILES=\
	l.h\
	elf.h\
    $TOP/include/ALL/8.out.h


CFLAGS=$CFLAGS -. -I.

<$TOP/mkfiles/mkone

# updated manually for now, because of syncweb
#$TOP/compilers/8c/enam.c: $TOP/include/ALL/8.out.h
#	@ { cd ../8c; mk enam.c }

enam.$O:	$TOP/compilers/8c/enam.c
	$CC $CFLAGS $TOP/compilers/8c/enam.c
