</$objtype/mkfile

TARG=8l
OFILES=globals.$O\
	asm.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	list.$O\
	enam.$O\
	compat.$O\
	elf.$O\

#PAD:	../8c/8.out.h\

HFILES=\
	l.h\
	elf.h\

BIN=/$objtype/bin
CFLAGS=$CFLAGS -. -I.
CFILES=${OFILES:%.$O=%.c}
#CFILES=${CFILES:enam.c=../8c/enam.c}
UPDATE=\
	mkfile\
	$HFILES\
	$CFILES\
	${TARG:%=/386/bin/%}\

</sys/src/cmd/mkone

#enam.$O:	../8c/enam.c
#	$CC $CFLAGS ../8c/enam.c
