</arm/mkfile

helloc: helloc.$O
	$LD -o $target $prereq        

%.$O: %.c
	$CC $CFLAGS $stem.c

TOP=../../..

TARGET=$TOP/ROOT/tests/5c

install:V:
	mkdir -p $TARGET; cp *.c mkfile $TARGET

clean:V:
	rm -f *.[$OS] [$OS].out helloc
