</arm/mkfile

all:V: helloc


helloc: helloc.$O
	$LD -o $target $prereq        

%.$O: %.c
	$CC $CFLAGS $stem.c

TOP=../../..

TARGET=$TOP/ROOT/tests/5c

install:V:
	mkdir -p $TARGET; cp *.c mkfile $TARGET

clean:V:
	rm -f *.[$OS] [$OS].out helloc

run:V:
    echo :c | 5i helloc

lib:V:
    objtype=arm; cd /sys/src/libc; mk clean; mk

all:V:
    mk clean; mk lib; mk; mk run
