# -*- sh -*-
TOP=..

DOC=Libcore

# set of noweb (.nw) files
# must be in the same order of the #include for syncweb multi files support
# to work
SRC_ORIG=Libcore.nw Libcore_extra.nw

L1=

# from list_graphics originally
L2= \
   ../include/ipc/thread.h\
   libthread/dial.c\
   libthread/ref.c\
   libthread/threadimpl.h\
   libthread/xincarm.c\
   libthread/xincport.h\
   libthread/globals.c\
   libthread/debug.c\
   libthread/id.c\
   libthread/exit.c\
   libthread/lib.c\
   libthread/note.c\
   libthread/rendez.c\
   libthread/386.c\
   libthread/sched.c\
   libthread/create.c\
   libthread/channel.c\
   libthread/main.c\
   libthread/kill.c\
   libthread/ioproc.c\
   libthread/iocall.c\
   libthread/chanprint.c\
   libthread/ioclose.c\
   libthread/iodial.c\
   libthread/ioopen.c\
   libthread/ioread.c\
   libthread/ioreadn.c\
   libthread/iosleep.c\
   libthread/iowrite.c\
   libthread/exec.c\

# libthread/arm.c
# libthread/xinc386.s
# tests/

SRC_VIEWS= $L1 $L2

<$TOP/docs/latex/mkcommon
