TOP=../../..
#objtype=arm
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

all:V: hello.exe funcs.exe longrun.exe

hello.exe:
     $CC $CFLAGS hello.c
     $LD $LDFLAGS -p -o $target hello.$O

funcs.exe:
     $CC $CFLAGS funcs.c
     $LD $LDFLAGS -p -o $target funcs.$O

longrun.exe:
     $CC $CFLAGS longrun.c
     $LD $LDFLAGS -p -o $target longrun.$O

clean:V:
     rm -f *.exe *.[58]


