TOP=../../..
#objtype=arm
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

all:V: hello funcs longrun

hello:
     $CC $CFLAGS hello.c
     $LD $LDFLAGS -p -o $target hello.$O

funcs:
     $CC $CFLAGS funcs.c
     $LD $LDFLAGS -p -o $target funcs.$O

longrun:
     $CC $CFLAGS longrun.c
     $LD $LDFLAGS -p -o $target longrun.$O

clean:V:
     rm -f hello funcs longrun

