TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIB=cc.a$O

OFILES=\
	    globals.$O\
        utils.$O\
	y.tab.$O\
	lex.$O\
	mac.$O\
	dcl.$O\
	acid.$O\
	pickle.$O\
	bits.$O\
	com.$O\
	scon.$O\
	funct.$O\
	sub.$O\
	com64.$O\
	compat.$O\
	dpchk.$O\
	omachcap.$O\


HFILES=cc.h	y.tab.h

YFILES=cc.y

CURCC=5c 6c 8c qc vc
OTHERCC=kc

<$TOP/mkfiles/mklib

#YFLAGS=-d -D 5

#ambiguous with mk-rc.byte, need :O:
#$LIB:	$LIBOBJ
#	iar vu $LIB $OFILES

#mac.$O:	macbody

everything:V:
	# mk the current compilers
	for(DIR in cc $CURCC){
		cd ../$DIR
		mk nuke
		mk install
	}
	# mk all the others with those
	for(DIR in cc $CURCC $OTHERCC){
		cd ../$DIR
		mk nuke
		mk installall
		mk clean
	}
