
HDIRS= 386/include arm/include    sys/include

all:V:
	mk clean
	cp -a ../include/386 386/include
	cp -a ../include/arm arm/include
	mkdir -p sys/include
	cp -a ../include/*.h sys/include

clean:V:
	rm -rf $HDIRS
