
HDIRS= 386/include arm/include    sys/include

all:V:
	mk clean
	cp -a ../include/386 386/include
	cp -a ../include/arm arm/include
	mkdir -p sys/include
	cp -a ../include/*.h sys/include
    cp -a ../ape/include/386 386/include/ape
    cp -a ../ape/include/arm arm/include/ape
    cp -a ../ape/include sys/include/ape

# safer to clean all the libs and binaries, you never know, you could
# get some no-up-to-date libs or binaries there
clean:V:
	rm -rf $HDIRS
	rm -f 386/bin/*
	rm -f 386/lib/*
