
HDIRS= 386/include arm/include mips/include sys/include

all:V:
	cp -a ../include/386 386/include
	cp -a ../include/arm arm/include
	cp -a ../include/mips mips/include
	mkdir -p sys/include
	cp -a ../include/*.h sys/include

clean:V:
        rm -rf $HDIRS
