TOP=../../..
<$TOP/mkfiles/$objtype/mkfile

PROGS=foobar

all:V: $PROGS

foobar: bar8l.$O foo8l.$O
	$LD -o $target $prereq

%.$O: %.c
	$CC $CFLAGS $stem.c

clean nuke:V:
	rm -f *.[$OS] [$OS].out $PROGS
