</$objtype/mkfile

PROGS=foobar

all:V: $PROGS

foobar: bar8l.$O foo8l.$O
	$LD -o $target $prereq

%.$O: %.c
	$CC $CFLAGS $stem.c

TOP=../../..

TARGET=$TOP/ROOT/tests/8l

install:V:
	mkdir -p $TARGET; cp *.c mkfile $TARGET

clean:V:
	rm -f *.[$OS] [$OS].out $PROGS
