TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIB=$ROOT/$objtype/lib/lib9p.a

OFILES=\
	auth.$O\
	dirread.$O\
	fid.$O\
	file.$O\
	intmap.$O\
	listen.$O\
	mem.$O\
	req.$O\
	parse.$O\
	post.$O\
	rfork.$O\
	srv.$O\
	thread.$O\
	uid.$O\
	util.$O\

HFILES=$TOP/include/ALL/9p.h

<$TOP/mkfiles/mksyslib

$O.ramfs: ramfs.$O $LIB
	$LD -o $target $prereq
