TOP=../../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=print
LIB=../lib/usb.a$O

OFILES=\
	main.$O\
	print.$O\

HFILES=\
	../lib/usb.h\
	../lib/usbfs.h\

<$TOP/mkfiles/mkone

BIN=/$objtype/bin/usb
CFLAGS=-I../lib $CFLAGS

$LIB:
	cd ../lib
	mk install
	mk clean

