#TOP=../../..
#<$TOP/mkfiles/arm/mkfile

hello: hello.5
     5l -o $target hello.5

%.5: %.s
     5a $prereq

#%.$O: %.s
#	$AS $stem.s

# could add -l
helloa: helloa.$O
	$LD -o $target $prereq        

clean nuke:V:
	rm -f *.5 5.out hello helloa

run:V:
    echo :c | 5i helloa
