#TOP=../../..
#<$TOP/mkfiles/arm/mkfile

# could add -l
helloa: helloa.$O
	$LD -o $target $prereq        

%.$O: %.s
	$AS $stem.s

clean nuke:V:
	rm -f *.[$OS] [$OS].out helloa

run:V:
    echo :c | 5i helloa
