TOP=../../../../..
<$TOP/mkfiles/$objtype/mkfile

LIB=usb.a$O

OFILES=\
	dev.$O\
	devs.$O\
	dump.$O\
	parse.$O\
	fs.$O\
	fsdir.$O\

HFILES=	usb.h usbfs.h

#coupling:
# a few dirs have in their mkfile: LIBD=../lib/usbdev.a$O
# so we need to make sure to clean it with mk nuke at least here
CLEANFILES=usbdev.a$O

<$TOP/mkfiles/mklib
