TOP=../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=dossrv

OFILES=\
	xfssrv.$O\
	xfile.$O\
	dosfs.$O\
	dossubs.$O\
	iotrack.$O\
	lock.$O\
	chat.$O\
	devio.$O\

HFILES=dat.h\
	dosfs.h\
	fns.h\
	iotrack.h\

<$TOP/mkfiles/mkone

xfssrv.$O:	errstr.h
