TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIBNAME=libpanel.a

OFILES=\
	button.$O\
	canvas.$O\
	draw.$O\
	edit.$O\
	entry.$O\
	event.$O\
	frame.$O\
	group.$O\
	init.$O\
	label.$O\
	list.$O\
	mem.$O\
	message.$O\
	pack.$O\
	popup.$O\
	print.$O\
	pulldown.$O\
	rtext.$O\
	scroll.$O\
	scrollbar.$O\
	slider.$O\
	textview.$O\
	textwin.$O\
	utf.$O\
	snarf.$O

HFILES=$TOP/include/ALL/panel.h pldefs.h $TOP/include/ALL/rtext.h

<$TOP/mkfiles/mksyslib
