TOP=../../..
<$TOP/mkfiles/arm/mkfile

all:V: helloc

helloc: helloc.$O
	$LD -o $target $prereq        

%.$O: %.c
	$CC $CFLAGS $stem.c



clean nuke:V:
	rm -f *.[$OS] [$OS].out helloc

run:V:
    echo :c | 5i helloc

lib:V:
    objtype=arm; cd /sys/src/libc; mk clean; mk

testall:V:
    mk clean; mk lib; mk; mk run
