TOP=../../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=disk

OFILES=\
	main.$O

LIBDOFILES=\
	disk.$O\
	scsireq.$O\
	scsierrs.$O\

HFILES=\
	scsireq.h\
	../lib/usb.h\
	../lib/usbfs.h\
	ums.h\

LIBD=../lib/usbdev.a$O
LIBU=../lib/usb.a$O
LIB=\
	$LIBD\
	$LIBU\

<$TOP/mkfiles/mkone

BIN=/$objtype/bin/usb

CFLAGS=-I../lib $CFLAGS

$LIBU:
	cd ../lib
	mk install
	mk clean

$LIBD:V: $LIBDOFILES
	ar vu $LIBD $newprereq
	rm $newprereq

scsierrs.c: /sys/lib/scsicodes mkscsierrs
	mkscsierrs > scsierrs.c

CLEANFILES=scsierrs.c
