TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libndb.a

OFILES=\
	csgetval.$O\
	csipinfo.$O\
	dnsquery.$O\
	ipattr.$O\
	ndbaux.$O\
	ndbcache.$O\
	ndbcat.$O\
	ndbconcatenate.$O\
	ndbdiscard.$O\
	ndbfree.$O\
	ndbgetipaddr.$O\
	ndbgetval.$O\
	ndbhash.$O\
	ndbipinfo.$O\
	ndblookval.$O\
	ndbopen.$O\
	ndbparse.$O\
	ndbreorder.$O\
	ndbsubstitute.$O\

HFILES=\
	$TOP/include/ALL/ndb.h\
	ndbhf.h

<$TOP/mkfiles/mksyslib

$O.out: testipinfo.$O
	$LD $prereq
