# -*- sh -*-
TOP=..

DOC=Make

# set of noweb (.nw) files
# must be in the same order of the #include for syncweb multi files support
# to work
SRC_ORIG=Make.nw Make_extra.nw

SRC_VIEWS= \
    mk/fns.h\
    mk/mk.h\
     mk/globals.c\
    mk/bufblock.c\
    mk/symtab.c\
    mk/rc.c\
    mk/word.c\
    mk/var.c\
    mk/plan9.c\
    mk/archive.c\
    mk/match.c\
    mk/env.c\
    mk/parse.c\
    mk/shprint.c\
    mk/rule.c\
    mk/lex.c\
    mk/file.c\
    mk/run.c\
    mk/graph.c\
    mk/mk.c\
    mk/recipe.c\
    mk/varsub.c\
     mk/dumpers.c\
    mk/main.c\
     mk/utils.c\

# also ROOT/tests/mk/hello.mk and maybe at some point more mkfiles

<$TOP/docs/latex/mkcommon

