MKSHELL=$PLAN9/bin/rc

</$objtype/mkfile

# libs used by the kernel
LIBS1=\
	libmemlayer\
	libmemdraw\
	libdraw\
	libip\
	libc\
	libmp\

LIBS2=\
	libString\
	libregexp\
	libbio\
	libthread\
	liblex\
	libmach\
	libauth\
	libauthsrv\

LIBS=$LIBS1 $LIBS2

#necessary for kernel!:
# font.c:21 incompatible types: "IND UINT" and "IND USHORT" for op "AS"

CMDS=cmd
SUBSYS=

none:VQ:
	echo mk all, install, clean, nuke, release, kernels, or libs

all install clean nuke:VQ:
	date
	for (i in $LIBS $CMDS) @{
		cd $i
		mk $target
	}
	date

installall:V:
	echo "installall not supported"

release:V:
	mk nuke
	rm -f /$objtype/lib/ape/*.a
	rm -f /$objtype/lib/*.a
	mk install
	mk clean

kernels:V:
	for (i in 9) @{
		cd $i
		mk clean
		mk install
		mk clean
	}

libs:V:
	date
	for (i in $LIBS) @{
		cd $i
		mk clean
		mk install
		mk clean
	}
	date

cleanlibs:V:
	for (i in $LIBS) @{
		cd $i
		mk clean
	}

updatelibs:V:
	for (i in $LIBS) @{
		cd $i
		mk update
	}
