</$objtype/mkfile

# libs used by the kernel
LIBS1=\
	libmemlayer\
	libmemdraw\
	libdraw\
	libip\
	libc\
	libmp\

# libs used by the core cmds (cc, lex, ...)
LIBS2=\
	libString\
	libregexp\
	libbio\
	libthread\
	liblex\
	libmach\
	libauth\
	libauthsrv\

# libs used by cmd/disk
LIBS3=\
        libdisk\
        lib9p\
        libsec\

# libs used by rio
LIBS4=\
        libframe\
        libplumb\
        libcomplete\

# libs used by aux/vga/db, gzip
LIBS5=\
        libndb\
        libflate\

#other: libhtml

LIBS=$LIBS1 $LIBS2 $LIBS3 $LIBS4 $LIBS5

CMDS=cmd

none:VQ:
	echo mk all, install, clean, nuke, release, cmds, kernels, or libs

all install clean nuke:VQ:
	for (i in $LIBS $CMDS 9/pc) @{
		cd $i
                echo DIR: $i
		mk $target
	}

installall:V:
	echo "installall not supported"

release:V:
	mk nuke
	rm -f /$objtype/lib/ape/*.a
	rm -f /$objtype/lib/*.a
	mk install
	mk clean

kernels:V:
	for (i in 9/pc) @{
		cd $i
                echo DIR: $i
		mk clean
		mk install
	}

cmds:V:
       for (i in $CMDS) @{
                cd $i
                echo DIR: $i
                mk clean
                mk cmds
                mk dirs
       }

libs:V:
	for (i in $LIBS) @{
		cd $i
                echo DIR: $i
		mk clean
		mk install
	}

cleanlibs:V:
	for (i in $LIBS) @{
		cd $i
		mk clean
	}

updatelibs:V:
	for (i in $LIBS) @{
		cd $i
		mk update
	}
