TOP=../../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=serial

OFILES=main.$O

LIBDOFILES=ftdi.$O serial.$O prolific.$O ucons.$O silabs.$O

HFILES=\
	../lib/usb.h\
	ftdi.h\
	prolific.h\
	serial.h\
	ucons.h\

LIBD=../lib/usbdev.a$O
LIBU=../lib/usb.a$O
LIB=\
	$LIBD\
	$LIBU\


<$TOP/mkfiles/mkone

BIN=/$objtype/bin/usb
CFLAGS=-I../lib $CFLAGS

$LIBU:
	cd ../lib
	mk install
	mk clean

$LIBD:V: $LIBDOFILES
	ar vu $LIBD $LIBDOFILES
