TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libmemlayer.a

OFILES=\
	draw.$O\
	lalloc.$O\
	layerop.$O\
	ldelete.$O\
	lhide.$O\
	line.$O\
	load.$O\
	lorigin.$O\
	lsetrefresh.$O\
	ltofront.$O\
	ltorear.$O\
	unload.$O\

HFILES=\
	$TOP/include/ALL/memlayer.h\
	$TOP/include/ALL/memdraw.h\
	$TOP/include/ALL/draw.h


<$TOP/mkfiles/mksyslib
