TOP=..

DIRS=diff misc git9

<$TOP/mkfiles/mkdirs

#-----------------------------------------------------------------------------

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang C

VERSION=1
DOC=VCS

SRC_ORIG=VCS.nw VCS_extra.nw

SRC_VIEWS=\
  misc/patch.c \
  diff/diff.c diff/diffdir.c diff/diff.h diff/diffio.c diff/diffreg.c \
  diff/merge3.c diff/util.c

<$TOP/docs/latex/mkcommon
