# -*- sh -*-
TOP=..

SYNCFLAGS=-lang shell

DOC=VCS

SRC_ORIG=VCS.nw VCS_extra.nw

SRC_VIEWS=dulwich.py \
  dulwich/__init__.py \
  dulwich/archive.py \
  dulwich/archive.py \
  dulwich/client.py \
  dulwich/client.py \
  dulwich/config.py \
  dulwich/config.py \
  dulwich/diff_tree.py \
  dulwich/errors.py \
  dulwich/fastexport.py \
  dulwich/file.py \
  dulwich/greenthreads.py \
  dulwich/hooks.py \
  dulwich/ignore.py \
  dulwich/index.py \
  dulwich/log_utils.py \
  dulwich/lru_cache.py \
  dulwich/object_store.py \
  dulwich/objects.py \
  dulwich/objectspec.py \
  dulwich/pack.py \
  dulwich/patch.py \
  dulwich/porcelain.py \
  dulwich/protocol.py \
  dulwich/reflog.py \
  dulwich/refs.py \
  dulwich/repo.py \
  dulwich/server.py \
  dulwich/walk.py \
  dulwich/web.py \

<$TOP/docs/latex/mkcommon
