TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=troff

OFILES=n1.$O\
	n2.$O\
	n3.$O\
	n4.$O\
	n5.$O\
	t6.$O\
	n6.$O\
	n7.$O\
	n8.$O\
	n9.$O\
	t10.$O\
	n10.$O\
	t11.$O\
	ni.$O\
	hytab.$O\
	suftab.$O\
	dwbinit.$O\

HFILES=tdef.h\
	fns.h\
	ext.h\
	dwbinit.h\



<$TOP/mkfiles/mkone

CFLAGS=-FTV -c -DSTRICT -DUNICODE -I$TOP/APE/include -I$TOP/APE/include/$objtype
CC=pcc
LDFLAGS=-L$TOP/ROOT/arch/$objtype/lib/ape

# claude: was sys/lib/tmac, sys/lib/troff/font, sys/lib/troff/term --
# this fork flattens /sys/lib/xxx to /lib/xxx (see ROOT/lib/{acid,ndb,
# font,...} for the established convention); pad.txt documents the
# same mapping ("tmac/ was /sys/lib/", "conf/ was /sys/lib/troff").
# These paths are looked up at runtime against the booted disk image's
# root, not this build tree, so they must match ROOT/lib/tmac and
# ROOT/lib/troff/{font,term} (typesetting/troff/{tmac,conf} moved
# there).
TMACDIR='"lib/tmac/tmac."'
FONTDIR="lib/troff/font"
NTERMDIR='"lib/troff/term/tab."'
TEXHYPHENS='"sys/lib/texmf/tex/generic/hyphen/hyphen.tex"'
DWBHOME='"/"'
TDEVNAME='"utf"'
NDEVNAME='"utf"'

$O.out:	$OFILES
	pcc $LDFLAGS -o $target $prereq

ni.$O:	ni.c $HFILES
	$CC $CFLAGS -DTMACDIR'='$TMACDIR ni.c

t10.$O:	t10.c $HFILES
	$CC $CFLAGS -DTDEVNAME'='$TDEVNAME t10.c

n1.$O:	n1.c $HFILES
	$CC $CFLAGS -DFONTDIR'='$FONTDIR -DNTERMDIR'='$NTERMDIR -DTEXHYPHENS'='$TEXHYPHENS -DALTHYPHENS'='$TEXHYPHENS -DDWBHOME'='$DWBHOME n1.c

n10.$O:	n10.c $HFILES
	$CC $CFLAGS -DNDEVNAME'='$NDEVNAME n10.c

n8.$O:	n8.c $HFILES
	$CC $CFLAGS -DTEXHYPHENS'='$TEXHYPHENS n8.c

dwbinit.$O:	dwbinit.c
	$CC $CFLAGS -DDWBHOME'='$DWBHOME dwbinit.c
