MKSHELL=$PLAN9/bin/rc

</$objtype/mkfile

#TODO: consolefs? depend? mouse? reboot? searchfs? statusbar
#LESS: mklatinkbd
TARG=\
	data2s\

BIN=/$objtype/bin/aux

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=%.c}\

</sys/src/cmd/mkmany
