TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=eqn

OFILES=main.$O\
	tuning.$O\
	diacrit.$O\
	eqnbox.$O\
	font.$O\
	fromto.$O\
	funny.$O\
	glob.$O\
	integral.$O\
	input.$O\
	lex.$O\
	lookup.$O\
	mark.$O\
	matrix.$O\
	move.$O\
	over.$O\
	paren.$O\
	pile.$O\
	shift.$O\
	size.$O\
	sqrt.$O\
	text.$O\
	y.tab.$O\

YFILES=eqn.y

HFILES=e.h y.tab.h

<$TOP/mkfiles/mkone

CC=pcc
LD=pcc
YFLAGS=-d -S
CFLAGS=-FTV -c
