TOP=..

DIRS=libhtml webfs  tcs misc  abaco mothra 

<$TOP/mkfiles/mkdirs

#-----------------------------------------------------------------------------

SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang C

VERSION=1
DOC=Browser

SRC_ORIG=Browser.nw Browser_extra.nw

#TODO: webfs misc/*.c, mothra? abaco? libhtmk?
# add also kernel devtls.c ?
SRC_VIEWS=

<$TOP/docs/latex/mkcommon

index:V:
   echo TODO
