</$objtype/mkfile

TARG=5a
OFILES=globals.$O\
	y.tab.$O\
	lex.$O\

#PAD:	../5c/5.out.h\
HFILES=\
	y.tab.h\
	a.h\

YFILES=a.y\

BIN=/$objtype/bin

LIB=../aa/aa.a$O


</sys/src/cmd/mkone
YFLAGS=-D1 -d

#lex.$O:	../cc/macbody ../cc/lexbody
