TOP=../../..
<$TOP/mkfiles/$objtype/mkfile

LIBNAME=libsec.a

# 2026-04-20: large merge of 9front's libsec (TLS 1.2 + AEAD ciphers + SNI
# + modern X.509). Kept principia's md5pickle/sha1pickle (used by hget) and
# asn1toDSApriv (used by security/auth/asn12dsa.c).
#
# 2026-04-21: NIST-curve ECC added. Instead of running 9front's mpc tool
# on secp*.mp at build time (mpc needs a Plan 9 host, we use goken to
# cross-compile from Linux), we ship a hand-written ecc.c based on
# 9front-hg-2014's self-contained affine-coordinate implementation, plus
# hand-written secp256r1.c / secp384r1.c / secp256k1.c that initialize
# domain parameters from SEC2 hex constants. Same pattern as libimg's
# pre-generated rgbv.h / ycbcr.h. Slower than 9front's jacobian/Montgomery
# path but enough for TLS client ECDSA cert verification and X25519 ECDHE.

CFILES= des.c desmodes.c desECB.c desCBC.c des3ECB.c des3CBC.c\
	aes.c aesni.c aesCBC.c aesCFB.c aesOFB.c aes_gcm.c\
	aes_xts.c\
	blowfish.c \
	hmac.c md5.c md5block.c md4.c sha1.c sha1block.c\
	sha2_64.c sha2_128.c sha2block64.c sha2block128.c\
	sha1pickle.c md5pickle.c\
	blake2s.c blake2sblock.c ripemd.c\
	poly1305.c\
	rc4.c\
	chacha.c chachablock.c\
	salsa.c\
	ccpoly.c\
	curve25519.c curve25519_dh.c\
	dh.c\
	pbkdf2.c scrypt.c hkdf.c\
	tsmemcmp.c\
	genrandom.c prng.c fastrand.c nfastrand.c\
	probably_prime.c smallprimetest.c genprime.c dsaprimes.c\
	gensafeprime.c genstrongprime.c\
	rsagen.c rsafill.c rsaencrypt.c rsadecrypt.c rsaalloc.c \
	rsaprivtopub.c x509.c decodepem.c \
	eggen.c egencrypt.c egdecrypt.c egalloc.c egprivtopub.c \
	egsign.c egverify.c \
	dsagen.c dsaalloc.c dsaprivtopub.c dsasign.c dsaverify.c \
	tlshand.c thumb.c readcert.c \
	idnstub.c \
	ecc.c secp256r1.c secp384r1.c secp256k1.c \

ALLOFILES=${CFILES:%.c=%.$O}

# cull things in the per-machine directories from this list
OFILES=	`{rc $TOP/mkfiles/reduce $O $objtype $ALLOFILES}

HFILES=$TOP/include/ALL/libsec.h\
	$TOP/include/ALL/libc.h\
	$TOP/include/ALL/mp.h\

CFLAGS=$CFLAGS -I../../../lib_math/libmp/port

<$TOP/mkfiles/mksyslib

$O.rsatest: rsatest.$O
	$LD -o $target $prereq
